# Generated by Django 4.2.7 on 2024-04-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsApp', '0003_detection_image_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='detection',
            name='image',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
        migrations.AddField(
            model_name='detection',
            name='results',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='score',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
