# Generated by Django 4.2.7 on 2024-04-08 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hsApp', '0005_rename_score_detection_scoredesc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hsApp.tags'),
        ),
    ]
