# Generated by Django 4.2.7 on 2024-04-08 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hsApp', '0006_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='title',
        ),
        migrations.AddField(
            model_name='detection',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hsApp.post'),
        ),
    ]
