# Generated by Django 4.2.7 on 2024-04-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsApp', '0007_remove_detection_desc_remove_detection_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='neCount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='nuCount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='poCount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
