# Generated by Django 5.0.4 on 2024-05-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsApp', '0008_alter_tags_necount_alter_tags_nucount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='totalCount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
